### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by v1gnesh** [IBM/tnz#132]
When switching between screens quickly, I find that I get `Keylock = 1` more often than I'd like.
Will it help to switch from the default python asyncio event loop to https://github.com/MagicStack/uvloop ?
If it improves the situation, it's fine if it isn't merged into the main branch, but is instead available as a flavour.
I suppose keeping dependencies to a minimum is a reason to not merge it into main.

**Comment by najohnsn** [comment]
I suspect this is related to #94. Unless you have 100 or more tnz sessions at the same time, I am very skeptical that the asyncio package would make a difference. 

I suspect you may be used to another emulator that buffers keyboard input while the keyboard is locked waiting for a response from the server. In which case, having zti do that kind of buffering would be the solution.

Do you agree with that, or maybe something else is going on?

**Comment by najohnsn** [comment]
Yeah, #94 wasn't the best reference. I know that buffering has been brought up before though. but I guess there is not an issue for it. I'm going to consider this an issue for it.

**Comment by najohnsn** [comment]
@v1gnesh, if you're willing.. I have a draft PR that I believe will address your issue. To install:
```sh
pip install git+https://github.com/IBM/tnz@keylock-buffer
```

**Comment by v1gnesh** [comment]
@najohnsn  Thank you. I don't know yet if a repository manager is capable of pulling PyPi stuff for pip via a git source. I'll try & report back.

**Comment by v1gnesh** [comment]
@najohnsn I tried the above command to install; looks like I can only install from a package (it can be obtained via a repository manager).

**Comment by najohnsn** [comment]
Interesting. I'm not familiar with your "repository manager" environment. Maybe you could download it from here?
https://github.com/IBM/tnz/archive/refs/heads/keylock-buffer.zip
Unzip it. Change directories to the parent of the tnz directory in the unzipped content. Then
```
python -m tnz.zti
```
I believe that Python will pick up the tnz module from that tnz directory instead of the installed tnz package.

**Comment by v1gnesh** [comment]
It's things like Artifactory JFrog or Nexus Repository.
They proxy packages from PyPI, but aren't capable of getting content from git directly.
Direct download from GH is not an option in some/many sites :) ... or at least frowned upon.
