### ISSUE TITLE
Latest Release and cacerts file

### ISSUE THREAD

**Issue by vbandaru** [IBM/tnz#163]
Thank you for this amazing project.

1. We are evaluating `tnz` for terminal automation in our org.  I see that no new releases since Nov 2023 and that quite a few fixes and enhancements since then. Wondering if you have timeline for new release with recent fixes?
2. With latest `0.4.0` version,  when SESSION_SSL_VERIFY enabled, it expects  `ibm-cacerts.pem` be available relative to repo. Can you please expose this via an env var for better portability. currently it chokes on below due to hardcoding of ca file.

```
if verifycert:
                context.load_verify_locations("ibm-cacerts.pem")
                self.__host_verified = True  # ? too soon ?
```

**Comment by najohnsn** [comment]
Glad you brought up the lack of releases. There is no official timeline/roadmap for releases. Unofficially, there was hope for one more enhancement to go into the next release. But it looks like other things will prevent that. So, `v0.5.1` has been created with current content.

With the latest security enhancements, when `SESSION_SSL_VERIFY=cert` (or `SESSION_SSL_VERIFY=hostname`) is used, the default certificate store will be used to establish trust. Is that sufficient for your purposes? If so, we can close this out.

**Comment by vbandaru** [comment]
Appreciate quick turnaround time with the release. Also verified the SSL and the initial test looks good.
