### ISSUE TITLE
DISPLAY mode issue

### ISSUE THREAD

**Issue by vbandaru** [IBM/tnz#165]
`HOST` mode doesn't show `zti` screen  when starting a session by importing `Ati` class.
```
from tnz.ati import Ati

ati = Ati()
try:
  ati.set("TRACE", "ALL") # Turn tracing on
  ati.set("LOGDEST", "demo.log") # Log file name
  ati.set("DISPLAY", "HOST") # HOST screens will be logged

  ati.set("SESSION_HOST", "999.999.999.999") 
  ati.set("SESSION_PORT", "23") 
  ati.set("SESSION", "A")  ### <------ FAILS at this point
  ati.wait(5)

finally:
 ati.drop("SESSION")
```

Above errors out with `CancelledError` as shown in image.

![image](https://github.com/user-attachments/assets/3d17f122-0bbc-4343-a334-7d39957d2cad)

Same works when importing `ati` as symbol

```
from tnz.ati import ati

try:
  ati.set("TRACE", "ALL") # Turn tracing on
  ati.set("LOGDEST", "demo.log") # Log file name
  ati.set("DISPLAY", "HOST") # HOST screens will be logged

  ati.set("SESSION_HOST", "999.999.999.999") 
  ati.set("SESSION_PORT", "23") 
  ati.set("SESSION", "A")
  ati.wait(5)

  ## ZTI screen display at this point.

finally:
 ati.drop("SESSION")
```

error reproducible with `0.4.0` and `0.5.1`

**Comment by najohnsn** [comment]
Thank you for reporting this problem!

As you may have already deduced, DISPLAY=HOST/`zti` works with the _current_ ati environment (`tnz.ati.ati`). It seems that the Ati object is not ensuring that it is the _current_ ati environment before using zti to show the screen.

You already have a workaround, but another way is to use `with ati` to make it your _current_ environment, like this:
```python
ati = Ati()
try:
 with ati:
  ati.set("TRACE", "ALL") # Turn tracing on
```

I will look into fixing this.

**Comment by vbandaru** [comment]
Thank you for the fix. I also notice with  `Ati` class import usage and display mode off, i see the performance seem to be way off for eg. 5s vs 15s with Ati class

**Comment by vbandaru** [comment]
@najohnsn

**Comment by najohnsn** [comment]
I've been making some changes from my initial draft fix. And testing it. Need to take one last look. If all goes well, it'll be in the end of the week.

**Comment by najohnsn** [comment]
I haven't had a chance to look at the 15s vs 5s. Certainly doesn't sound like _performance_ though.
