### ISSUE TITLE
Keylock timing

### ISSUE THREAD

**Issue by vbandaru** [IBM/tnz#169]
how to check if I am on the right screen without hard waits?

Here is my flow of a simple case ( i have more complex case but below should explain my issue)

1. goto login screen
2. enter userid and password, hit enter
3. two possibilites at this point, login screen may error out, at this point, I need to exit by logging an error OR login is successful, at this point, I will be automatically taken to next screen and program proceeds with next set of commands.

after I hit enter as in step 2,  the screen may take unknown amount of time, to goto next screen or error out on the current screen, 

I have something like below, 

```
retries = 0
login_failure=False
while (retries < 60): # max 60 retries.
  if  ati.value('keylock')  == 0 :
     if ati.scrhas("LOGIN SCREEN"): # still on login screen, possibly some error on screen
        login_failure = True
     break
     ati.wait(1) # 1 sec wait between checks to see keylock is 0
     retries = retries + 1

if login_failure:
   # log error
    error = ati.extract(...) # extract error from screen
   return error
else:
  # more commands on next screen
  # ....
```

in my environment, i see that it takes atleast 4 attempts (~4+ seconds) or sometimes more for keylock to be available  before I can take any action on current screen or next next screens. This is  considerably big amount of time for a synchornous request/response model. is there way to improve this logic?

**Comment by najohnsn** [comment]
See examples/logon.py in the repo. You don't want to wait for a period of time and try to do more _updates_. You want to wait for your target screen/fields to be sent from the server and use that to trigger the _updates_. I've written plenty of code that _also_ waits for the keyboard to be unlocked. So adding that to the lambda/function on the wait can be good. But you can often get away without it.

**Comment by najohnsn** [comment]
Here is an example of how I might convert your example code:
```python
ati.set("MAXWAIT", 60)
ati.wait(lambda: not ati.scrhas("LOGON SCREEN") and ati.value("KEYLOCK") == "0")
login_failure = ati.value("RC") == "0"
if login_failure:
   error = ati.extract(ati.EOL, ati.FIRST, "IKJ", (0, -3))
   return error
else:
  # more commands on next screen
  # ....
```

**Comment by vbandaru** [comment]
Thank you. Definitely looks cleaner.
