### ISSUE TITLE
Ati class usage holds session

### ISSUE THREAD

**Issue by vbandaru** [IBM/tnz#174]
with `Ati` class import, it seems to be holding sessions on the host even after `ati.drop('SESSION')` part of a load test with multiple users. Confirmed with `0.5.1` and `0.5.2`.  This behavior is not seen with `ati` symbol usage.

```

ati = Ati()
try:
  ati.set("TRACE", "ALL") # Turn tracing on
  ati.set("LOGDEST", "demo.log") # Log file name
  ati.set("DISPLAY", "HOST") # HOST screens will be logged

  ati.set("SESSION_HOST", "999.999.999.999") 
  ati.set("SESSION_PORT", "23") 
  ati.set("SESSION", "A") 
  ati.wait(5)

finally:
 ## ati.send("[pa2]") # alt-home to logoff
 ati.drop("SESSION")
```

**Comment by najohnsn** [comment]
Thank you for your contribution! I don't expect that `ati.ati` would behave any different from `ati.Ati()`. So, it might depend on how you observed this behavior? Was it that you used one `Ati()` to logon, dropped the session, then used another `Ati()` to login again and observed the first is still logged in? Or something else?

**Comment by vbandaru** [comment]
@najohnsn Initially i had `ati` usage, never noticed any session holdings. but when I switch to `Ati` to account for multi sessions in prep for load test, time to time I see sessions holding up on host.

Also on related note,  what could possibly causing this issue with latency with `Ati` that I mentioned here https://github.com/IBM/tnz/issues/165#issuecomment-2457628186

Thank you for the fix. looking forward for the next release.

**Comment by vbandaru** [comment]
@najohnsn  

not sure this helps. When session is held, the login flow of my terminal wouldn't allow going into the mainframe program and it would stop right at the login screen with error: `TSS7172E YOUR ACCESSOR ID IS ALREADY IN USE ON TERMINAL terminal`. 

Above behaviour is same as when I  login in using pcom window to browse any program, and simultaneously open another pcom window with same login info, later would give `TSS7172E` error same as above when attempting using `tnz`

**Comment by najohnsn** [comment]
That helps a bit. What was your program doing that was connected to the session? Did it terminate? Was it doing some non-tnz stuff?

**Comment by vbandaru** [comment]
the usecase is mostly readonly, which just extracts data of the screens after entering data inputs.

here is high level flow:

1. login with `ati.send("logon applid=<region>[enter]")`
2. on next screen userid/password
3. choose program with `ati.send("PROG1[enter]")`
4. bunch of input field entry with `ati.send(...)`
5. then do data extracts with `ati.extract(...)` 
6. in finally block, do a `ati.drop('SESSION)`

**Comment by vbandaru** [comment]
@najohnsn

**Comment by najohnsn** [comment]
I never experienced this "held session" problem in my programs. I _suspect_ that is because I either reuse the same Ati for other things after dropping sessions, or the program ends (i.e. the python interpreter terminates). I don't believe you are using the same Ati, so if the 2nd case applied to you? (The program terminating). If your Python interpreter is terminating after dropping the session and it is _still_ "held", then maybe there is another problem lurking?

**Comment by vbandaru** [comment]
@najohnsn 
I use `flask`  and expose rest api endpoint that would  invoke the  `tnz` code wrapped in a method which would return extracted data. so the python interpreter wouldn't stop in my case.

**Comment by najohnsn** [comment]
Thank you! Now it makes sense to me why you ran into this bug. I believe the fix that is out there in the latest release should address your issue.

**Comment by vbandaru** [comment]
@najohnsn  so i tried with .53 version. Ati() usage still reports of accessor in use error i noted above. 

At this point, Let me know if need any further logs that would enable pinpointing the issue also let me if i need to enable any  trace options.

I dont have an option to post minimal working code Outside of work, wondering is there a terminal out there that we can test this against

**Comment by najohnsn** [comment]
We can look into this further. But you might consider doing a logoff before dropping the session in order to avoid these sorts of issues.
