### ISSUE TITLE
(Request) Easily specify EBCDIC codepage to use

### ISSUE THREAD

**Issue by paullilley** [IBM/tnz#175]
Currently the tns encoding defaults to 'cp1047' which supports the Latin-1 character set.
This can result in the terminal showing some characters incorrectly if the mainframe uses a different codepage.  
For example, a mainframe using cp277 (Danish/Norwegian) will have the letter Ø displayed as @.

I did not find an obvious way to pass a specific codepage to the Emulator - or have I missed something?

A workaround is to explicitly instantiate ati, set the codepage and pass this to the Emulator:
```python 
from tnz.py3270 import Emulator
from tnz.ati import ati
ati.set("SESSION_CODE_PAGE", "cp277")
em = Emulator(
    visible=True,
    args=[
        "-trace",
        "-tracefile",
        "tnz_example.log",
    ],
    ati=ati
)
```

It would be nicer to be able to pass the codepage as an argument to the Emulator constructor, e.g.
```python 
from tnz.py3270 import Emulator
em = Emulator(
    visible=True,
    args=[
        "-trace",
        "-tracefile",
        "tnz_example.log",
        "-session_code_page", 
        "cp277"
    ]
)
```

I'm happy to put together a PR for this if you'd like and would appreciate input on naming the argument/option.

**Comment by najohnsn** [comment]
The purpose of py3270.py is to mimic/reuse the py3270 repo api. In this case, the options are x3270/s3270 options. Specifically, charset: https://x3270.bgp.nu/Unix/x3270-man.html#Character-Sets

So, I think the name of the option is already decided. Looks like it would involve some translation though.

If you are willing to contribute, I'd certainly be agreeable to merging a PR with an enhancement to support "-charset".
