### ISSUE TITLE
Could not find a version that satisfies the requirement tnz

### ISSUE THREAD

**Issue by moshix** [IBM/tnz#19]
Ran into this issue during pip install tzi:

:~# pip install ebcdic tnz
Collecting ebcdic
  Downloading https://files.pythonhosted.org/packages/0d/2f/633031205333bee5f9f93761af8268746aa75f38754823aabb8570eb245b/ebcdic-1.1.1-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 5.6MB/s 
Collecting tnz
  Could not find a version that satisfies the requirement tnz (from versions: )
No matching distribution found for tnz

**Comment by najohnsn** [comment]
Python 3.6 or later is required. What version of python are you using? (i.e. check `pip --version` and `python --version`)

**Comment by najohnsn** [comment]
@moshix have you gotten this working or have you identified that you don't have the Python requirement satisfied?

**Comment by moshix** [comment]
yes, got the pip install working. But it's not clear after doing the pip what to do to run zti. 

thanks

M
