### ISSUE TITLE
MacOS Initial Use Support

### ISSUE THREAD

**Issue by KipTwitchell** [IBM/tnz#32]
First impressions are only available once, so thought I would give the project mine.  Was given at link by Ian Mitchell when looking for an alternative to Host on Demand (had problems with TLS support there).  

Was able quite easily to figure out python install, followed by zti based upon Readme.  Help Goto didn't quite get me far enough though.  Guessed from error message: 
```
File "/usr/local/lib/python3.10/site-packages/tnz/tnz.py", line 3689, in __connect await loop.create_connection(protocol, host, port," 
```
I needed to put host on the goto command, and port 992.  

Couldn't determine what to do next with final message of:
```
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
SESLOST = '[my host name]'
```

I'm willing to donate some text to the readme for a Mac User if I could get it working.

**Comment by najohnsn** [comment]
For what it's worth, your issue doesn't sound Mac specific - the process of connecting to a 3270 server is very platform-independent. 

My first thought is to make sure you specify the fully-qualified hostname, like myhost.some.thing.com. The default is to use a secure connection to port 992, so appending ":992" shouldn't be needed - though it shouldn't hurt either. 

If the server doesn't support secure connections, you need to first use the zti command line to set SESSION_SSL to 0. There is an animated gif with an example at https://medium.com/theropod/3270-is-terminal-84d0af522cfd.

**Comment by KipTwitchell** [comment]
You're right about Mac; if I come up with something, I'll add it.  Have the fully qualified host name, which works for HOD. Using your suggestion, I dropped the 992.  I get a flash of a screen for a moment, then it drops.  Now getting:
```
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)
```

**Comment by KipTwitchell** [comment]
HOD configuration for server which works is:
- Use JSSE: Yes
- TLS Version: 1.2
- Telnet-Negotiated: No
- FIPS Mode: No
- Server Authenticate: No
- Add MSIE....:  No
- Send Certificate:  No

**Comment by najohnsn** [comment]
My guess for that error is that you are using Python 3.10 and SSL is basically rejecting the connection because it is not secure enough. Python 3.10 is pretty aggressive in causing failures for algorithms/options that are not secure enough. 

The best course of action is to request that the server be updated to support security best practices in terms of supported encryption algorithms and key sizes. I had worked with some z/OS admins to do just this for this reason. 

The other option is to try to use the "less secure" way that the server is "forcing". If this is a problem with the changes in Python 3.10, doing `export ZTI_SECLEVEL=1` before starting zti should accept the "less secure" option by downgrading the level from 2 to 1.

**Comment by KipTwitchell** [comment]
That worked.  Thanks for that.

Is there some way I could take this conversation and add a document that helps someone through this?  Opening to giving the project 30 minutes of my time in exchange for your help here if you have some direction.

I'll also see if there are other gotcha's as I progress in using it further, and comment here as well.

**Comment by KipTwitchell** [comment]
was able to get through initial logon all the way to TSO, but when I tried ISPF, got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/zti", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 3850, in main
    zti.cmdloop(intro)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 200, in cmdloop
    super().cmdloop(intro=text)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 675, in do_goto
    r2d2rv = self.__r2d2(self.stdscr, _WAIT_GOTO, -1)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 2184, in __r2d2
    self.__display(win, not show)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 1918, in __display
    self.write(tns, faddr, saddr, eaddr)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 1443, in write
    self.__write_group(tns, faddr, saddr1, eaddr1)
  File "/usr/local/lib/python3.10/site-packages/tnz/zti.py", line 3600, in __write_group
    text = tns.scrstr(caddr1, endpos)
  File "/usr/local/lib/python3.10/site-packages/tnz/tnz.py", line 1503, in scrstr
    strl.append(codec_info[cii].decode(bytes1)[0])
KeyError: 241
```

**Comment by KipTwitchell** [comment]
Also, the Readme is out of date with the Pip command; needs  to  be Pip3 now

**Comment by najohnsn** [comment]
That's great! You can thank Peter Kidwell for that `ZTI_SECLEVEL` support. :-)

That would be great if you could contribute some documentation! See [CONTRIBUTING](https://github.com/IBM/tnz/blob/main/CONTRIBUTING.md). That would be the way to go to update the readme for pip3. Though, maybe you are thinking of content that would be best for the [wiki](https://github.com/IBM/tnz/wiki). Unfortunately, that's not as easy. But I could give you access to that if that's what you would like to do.

That `KeyError: 241` is a new one. :-(

That _looks like_ the server/host is referencing _character set 241_, but tnz isn't going to know anything about _character set 241_. Usually, the character set number is 0 to reference your main code page that you're using. Applications like ISPF may use graphic escapes to reference character set 1 - code page 310.

Do you get that error immediately when entering ISPF?

**Comment by KipTwitchell** [comment]
@najohnsn, your update fixed the issue. As you noted, 

"instructions that are causing zti to fail when trying to convert the data to a string to display:
2022-08-26 11:47:58,731 WLAA  Set Attribute Type=0x43 Value=0xf1
the 0x43 indicates to set the character set. the 0xf1=241 is the "key" that it errors on
:+1:
1

"i might guess that the value of 0xf1 is intended to behave as 0x01. In other words, an ebcdic "1" is being passed instead of a binary 1. Character set 0x01 is typically used for "character-drawing" - drawing boxes, lines, and such. Each time 0x43/0xf1 is used, it is used for a single chacter - either by itself or repeated some number of times."

Nice update.  Fully functional for me it looks like.  Thanks for being so responsive.
