### ISSUE TITLE
zti does not respect /etc/hosts

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [IBM/tnz#35]
When opening a session and specifying a host defined within /etc/hosts, zti ignores me and does a dns lookup, then fails it with:
```
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Which would be true for this particular host if I didn't have the mapping in /etc/hosts, but I do and other programs like ssh respect it.

**Comment by najohnsn** [comment]
I wonder why Python doesn't use /etc/hosts?

**Comment by 1000TurquoisePogs** [comment]
More system info:
python 3.7.8
ubuntu 18.04.6 LTS

**Comment by najohnsn** [comment]
I see the problem in `zti.;py`!
```
            if "." not in hostname:
                fqdn = socket.getfqdn()
                fqdn = fqdn.split(".")
                if len(fqdn) > 1:
                    hostname += "."+".".join(fqdn[1:])
```

It is making an incorrect assumption that if you don't have a '.' in the hostname that you must want zti to append the _suffix_ of the local machine.

That just looks wrong and should be deleted.
