### ISSUE TITLE
Sample Code for ATI with condition checking

### ISSUE THREAD

**Issue by sunil390** [IBM/tnz#69]
This is a wonderful tool. Can we have few samples with condition checking included to be closer to real life scenarios ?

**Comment by sunil390** [comment]
Specifically looking for how to capture the RC from ati.scrhas

**Comment by sunil390** [comment]
Finally could make it work by boolean check. 
```
if ati.scrhas("String") == True:
```
Sample Attached here...
[atisampletocheckstc.txt](https://github.com/IBM/tnz/files/11641686/atisampletocheckstc.txt)

**Comment by sunil390** [comment]
Thank you Neil and other IBMers to make this tool opensource. Looking forward to more documenation and features :-)

**Comment by najohnsn** [comment]
Thanks for opening this issue. I think that providing more samples is a great idea!

As you've discovered, scrhas() returns a bool. The https://github.com/IBM/tnz/blob/main/examples/logon.py sample implicitly demonstrates that through its use in lambda functions passed to wait(). 

You can use ati.value('rc') to check the rc. That rc can be used for more _detailed_ information. There should be a sample that demonstrates the used of rc.
